# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b950a7f9277805a5560b2708bdacb26d7ff019573d45e999a43c5d6ea3cb1e7131ff062ccd069b6b249ca55c30d4280d17e5fe3cce8f329abb8ec2088fe1a11e

test:
  secret_key_base: b86bd861a31edd289586cd4ef8b5f8a720e01261c324ee37e4068e926b00ac07230fdc4f606d9b96cf70f975f535d4eab41d94ea8d7537c21f56010792c2e404

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
